name: CI/CD Pipeline for development

on:
  push:
    branches: develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
   
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.CI_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
    
      - name: Build and Push Docker Image
        run: |
          export IMAGE_NAME="ai-engine-barcode"
          export IMAGE_TAG=$(cat ./VERSION)
          echo $IMAGE_NAME:$IMAGE_TAG
          cd scripts/docker-management
          ./build-image.sh
          
          printf "%s\n" """${{secrets.PRIVATE_KEY}}""" > ./privatekey
          chmod 400 ./privatekey
          docker save $IMAGE_NAME:$IMAGE_TAG | bzip2 | ssh -o StrictHostKeyChecking=no  -i ./privatekey ${{ secrets.DEV_USER_NAME }}@${{ secrets.DEV_IP }} docker load

      - name: Run Docker Image
        uses: appleboy/ssh-action@v1.0.0
        env:
          IMAGE_NAME: "ai-engine-barcode"
          IMAGE_TAG: "0.1.0"
          PORT: "9002"
        with:
          envs: IMAGE_NAME, IMAGE_TAG, PORT
          host: ${{ secrets.DEV_IP }}
          username: ${{ secrets.DEV_USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/infrastructure-server/scripts/docker-management
            ./run-image.sh $IMAGE_NAME $IMAGE_TAG $PORT


