name: CI/CD Pipeline for production

on:
  push:
    branches: main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
   
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
    
      - name: Build and Push Docker Image
        run: |
          cd scripts/docker-management
          chmod +x enable-scripts.sh
          ./enable-scripts.sh
          ./build-image.sh
          ./push-image.sh
       
      # Todo : use ssh key to login
      # Todo : add unit tests check
      # Todo : add script git-pull 
      - name: Pull - Run Docker Image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 37.27.17.87
          username: root
          password: TALRevweF7MavErat3bU
          script: |
            cd api-platform/scripts
            chmod +x enable-scripts.sh
            ./enable-scripts.sh
            ./pull-image.sh
            ./run-image.sh
            ./delete-images.sh
    


