name: CI/CD Pipeline for development

on:
  push:
    branches: develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
   
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
    
      - name: Build and Push Docker Image
        run: |
          export IMAGE_NAME="ai-engine-barcode"
          export IMAGE_TAG=$(cat ./VERSION)
          echo $IMAGE_NAME:$IMAGE_TAG
          cd scripts/docker-management
          echo "${{secrets.PRIVATE_KEY}}" > ./privatekey
          cat ./privatekey
          echo ${{ secrets.DEV_USER_NAME }}@${{ secrets.DEV_IP }}
          docker save $IMAGE_NAME:$IMAGE_TAG | bzip2 | ssh  -i ./privatekey ${{ secrets.DEV_USER_NAME }}@${{ secrets.DEV_IP }} docker load
    


