name: CI/CD Pipeline for development

on:
  push:
    branches: develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
   
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.CI_TOKEN }}

      - name: Save Environment Variables
        run: |
          echo export IMAGE_NAME="ai-engine-barcode" >> .env
          echo export IMAGE_TAG=$(cat ./VERSION) >> .env
          cat .env

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
    
      - name: Build and Push Docker Image
        run: |
          cd scripts/docker-management
          cat .env
          echo $IMAGE_NAME:$IMAGE_TAG
       
      - name: Copy image to remote server
        run: docker save $IMAGE_NAME:$IMAGE_TAG | bzip2 | pv | ssh ai-engine-develop docker load
    


